# Generated by Django 3.1 on 2023-10-28 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_auto_20231028_1413'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employer',
            new_name='EmployerProfile',
        ),
    ]
