# Generated by Django 3.1 on 2023-10-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_auto_20231028_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='headprofile',
            name='full_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='full_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
