# Generated by Django 3.1 on 2023-11-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0009_auto_20231028_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='cgpa',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='spi_semester1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='spi_semester2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='spi_semester3',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='spi_semester4',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='spi_semester5',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='spi_semester6',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='spi_semester7',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='spi_semester8',
            field=models.FloatField(null=True),
        ),
    ]
