# Generated by Django 3.1 on 2023-11-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0010_auto_20231108_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='cgpa',
            field=models.FloatField(editable=False, null=True),
        ),
    ]
