# Generated by Django 3.1 on 2023-11-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0011_auto_20231108_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
