# Generated by Django 3.1 on 2023-10-28 16:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='application_date',
        ),
        migrations.RemoveField(
            model_name='application',
            name='student_name',
        ),
        migrations.AddField(
            model_name='application',
            name='applied_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='application',
            name='interview_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='is_shortlisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
